databases:
  - name: caja
    databaseName: caja
    user: caja

services:
  - type: web
    name: caja
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: caja
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
