databases:
  - name: istante-db
    region: singapore
    databaseName: istante
    user: istante

services:
  - type: redis
    name: istante-cache
    region: singapore
    ipAllowList: [] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lfu # optional (defalts to allkeys-lru).  Rails recommends allkeys-lfu as a default.
  - type: web
    name: istante-web
    region: singapore
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: istante-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: istante-cache
          property: connectionString
